name: Update Order Status

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update-order-status:
    runs-on: ubuntu-latest

    steps:
      - name: Call Order Status Cron
        run: |
          curl -4 -L \
            --fail \
            --retry 3 \
            --retry-delay 5 \
            --connect-timeout 30 \
            --max-time 120 \
            -A "Mozilla/5.0" \
            "https://apnasmm.site.je/crons/orders.php"
